apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      affinity:
        # 1) 사용할 노드 범위를 kube-node1, kube-node2로 제한
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kube-node1
                      - kube-node2

        # 2) 같은 app=django 파드끼리는 같은 노드에 같이 못 있게 강제
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - django
              topologyKey: kubernetes.io/hostname

      imagePullSecrets:
        - name: dockerhub-cred

      containers:
        - name: django
          image: jjunch/django:35
          imagePullPolicy: Always
          env:
            - name: DJANGO_DB_ENGINE
              value: django.db.backends.postgresql
            - name: DJANGO_DB_NAME
              value: mysite
            - name: DJANGO_DB_USER
              value: mysite
            - name: DJANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-password
            - name: DJANGO_DB_HOST
              value: postgres-svc
            - name: DJANGO_DB_PORT
              value: "5432"
          ports:
            - containerPort: 8000
